@startuml 0
actor Декан
actor Преподаватель
actor Студент
actor Система

usecase "Прием студентов"
usecase "Отчисление студентов"
usecase "Учет успеваемости"
usecase "Перевод студентов"
usecase "Ведение документации"

Студент -->> "Прием студентов"
Студент -->> "Учет успеваемости"
Студент -->> "Перевод студентов"

Декан -->> "Отчисление студентов"
Декан -->> "Перевод студентов"
Декан -->> "Ведение документации"

Преподаватель -->> "Учет успеваемости"

"Прием студентов"..> "Учет успеваемости"
"Отчисление студентов"..> "Прием студентов"
"Учет успеваемости"..> "Перевод студентов"
"Перевод студентов"..> "Ведение документации"

Система -->> "Прием студентов"
Система -->> "Отчисление студентов"
Система -->> "Учет успеваемости"
Система -->> "Перевод студентов"
Система -->> "Ведение документации"
@enduml