@startuml 1.1
actor Декан
actor Студент
actor Администратор

usecase "Прием студента" as UC1
usecase "Отчисление студента" as UC2
usecase "Перевод студента в другую группу" as UC3
usecase "Перевод студента на другой курс" as UC4
usecase "Учет успеваемости студента" as UC5

Декан -> UC1
Декан -> UC2
Декан -> UC3
Декан -> UC4
Декан -> UC5

Студент -> UC1
Студент -> UC2
Студент -> UC3
Студент -> UC4

Администратор -> UC5
@enduml