@startuml 1
skinparam componentStyle um12

package "Деканат"{
    [Информационная система] as IS
}

IS - [Список студентов на зачисление]
IS - [Список студентов на отчисление]
IS - [Учет успеваемости]
IS - [Учет студентов]
IS - [Группа]
IS - [Курс]

[Список студентов на зачисление] ..> [Учет студентов]: содержит
[Список студентов на отчисление] ..> [Учет студентов]: содержит
[Учет успеваемости] ..> [Учет студентов]: содержит
[Группа] ..> [Учет студентов]: содержит
[Курс] ..> [Учет студентов]: содержит

@enduml