@startuml 1
class Student {
  - id: string
  - name: string
  - group: Group
  - course: Course
  + enroll()
  + expel()
  + transferGroup(group: Group)
  + transferCourse(course: Course)
}

class Group {
  - id: string
  - name: string
  - students: List<Student>
  + addStudent(student: Student)
  + removeStudent(student: Student)
}

class Course {
  - id: string
  - name: string
  - students: List<Student>
  + addStudent(student: Student)
  + removeStudent(student: Student)
}

class Deanery {
  - students: List<Student>
  - groups: List<Group>
  - courses: List<Course>
  + acceptStudent(student: Student)
  + expelStudent(student: Student)
  + transferStudent(student: Student, group: Group)
  + transferStudent(student: Student, course: Course)
  + getStudentPerformance(student: Student)
}

Student --* Group
Student --* Course
Deanery --* Student
Deanery --* Group
Deanery --* Course
@enduml