@startuml 2
actor Декан
actor Система
actor Студент

Студент -> Система: Подать заявление на поступление
Система -> Декан: Рассмотреть заявление
Декан -> Система: Принять студента
Система -> Студент: Зачислить студента

Студент -> Система: Сдать сессию
Система -> Декан: Предоставить ведомость успеваемости
Декан -> Система: Утвердить ведомость
Система -> Студент: Перевести на следующий курс

Студент -> Система: Подать заявление на перевод в другую группу
Система -> Декан: Рассмотреть заявление
Декан -> Система: Одобрить перевод
Система -> Студент: Перевести в другую группу
@enduml